//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ProtobufParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ProtobufParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IProtobufParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] ProtobufParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.fileElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileElement([NotNull] ProtobufParser.FileElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.commentDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommentDecl([NotNull] ProtobufParser.CommentDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.syntaxDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSyntaxDecl([NotNull] ProtobufParser.SyntaxDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.syntaxLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSyntaxLevel([NotNull] ProtobufParser.SyntaxLevelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] ProtobufParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.emptyDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyDecl([NotNull] ProtobufParser.EmptyDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.packageDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageDecl([NotNull] ProtobufParser.PackageDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.packageName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageName([NotNull] ProtobufParser.PackageNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.importDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportDecl([NotNull] ProtobufParser.ImportDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.importedFileName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportedFileName([NotNull] ProtobufParser.ImportedFileNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeName([NotNull] ProtobufParser.TypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.qualifiedIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedIdentifier([NotNull] ProtobufParser.QualifiedIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.fieldDeclTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDeclTypeName([NotNull] ProtobufParser.FieldDeclTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageFieldDeclTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageFieldDeclTypeName([NotNull] ProtobufParser.MessageFieldDeclTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.extensionFieldDeclTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtensionFieldDeclTypeName([NotNull] ProtobufParser.ExtensionFieldDeclTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.oneofFieldDeclTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneofFieldDeclTypeName([NotNull] ProtobufParser.OneofFieldDeclTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.methodDeclTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDeclTypeName([NotNull] ProtobufParser.MethodDeclTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.fieldDeclIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDeclIdentifier([NotNull] ProtobufParser.FieldDeclIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageFieldDeclIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageFieldDeclIdentifier([NotNull] ProtobufParser.MessageFieldDeclIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.extensionFieldDeclIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtensionFieldDeclIdentifier([NotNull] ProtobufParser.ExtensionFieldDeclIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.oneofFieldDeclIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneofFieldDeclIdentifier([NotNull] ProtobufParser.OneofFieldDeclIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.methodDeclIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDeclIdentifier([NotNull] ProtobufParser.MethodDeclIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.fullyQualifiedIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullyQualifiedIdentifier([NotNull] ProtobufParser.FullyQualifiedIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.optionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionDecl([NotNull] ProtobufParser.OptionDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.compactOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompactOptions([NotNull] ProtobufParser.CompactOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.compactOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompactOption([NotNull] ProtobufParser.CompactOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.optionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionName([NotNull] ProtobufParser.OptionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.optionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionValue([NotNull] ProtobufParser.OptionValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.scalarValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalarValue([NotNull] ProtobufParser.ScalarValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.intLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntLiteral([NotNull] ProtobufParser.IntLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLiteral([NotNull] ProtobufParser.FloatLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.specialFloatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialFloatLiteral([NotNull] ProtobufParser.SpecialFloatLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageLiteralWithBraces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageLiteralWithBraces([NotNull] ProtobufParser.MessageLiteralWithBracesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageTextFormat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageTextFormat([NotNull] ProtobufParser.MessageTextFormatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageLiteralField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageLiteralField([NotNull] ProtobufParser.MessageLiteralFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageLiteralFieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageLiteralFieldName([NotNull] ProtobufParser.MessageLiteralFieldNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.specialFieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialFieldName([NotNull] ProtobufParser.SpecialFieldNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.extensionFieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtensionFieldName([NotNull] ProtobufParser.ExtensionFieldNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.typeURL"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeURL([NotNull] ProtobufParser.TypeURLContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] ProtobufParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageValue([NotNull] ProtobufParser.MessageValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageLiteral([NotNull] ProtobufParser.MessageLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.listLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListLiteral([NotNull] ProtobufParser.ListLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.listElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListElement([NotNull] ProtobufParser.ListElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.listOfMessagesLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListOfMessagesLiteral([NotNull] ProtobufParser.ListOfMessagesLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageDecl([NotNull] ProtobufParser.MessageDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageName([NotNull] ProtobufParser.MessageNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageElement([NotNull] ProtobufParser.MessageElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageFieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageFieldDecl([NotNull] ProtobufParser.MessageFieldDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.fieldDeclWithCardinality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDeclWithCardinality([NotNull] ProtobufParser.FieldDeclWithCardinalityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.fieldCardinality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldCardinality([NotNull] ProtobufParser.FieldCardinalityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.fieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldName([NotNull] ProtobufParser.FieldNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.fieldNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldNumber([NotNull] ProtobufParser.FieldNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.mapFieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapFieldDecl([NotNull] ProtobufParser.MapFieldDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.mapType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapType([NotNull] ProtobufParser.MapTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.mapKeyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapKeyType([NotNull] ProtobufParser.MapKeyTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.groupDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupDecl([NotNull] ProtobufParser.GroupDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.oneofDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneofDecl([NotNull] ProtobufParser.OneofDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.oneofName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneofName([NotNull] ProtobufParser.OneofNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.oneofElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneofElement([NotNull] ProtobufParser.OneofElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.oneofFieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneofFieldDecl([NotNull] ProtobufParser.OneofFieldDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.oneofGroupDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneofGroupDecl([NotNull] ProtobufParser.OneofGroupDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.extensionRangeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtensionRangeDecl([NotNull] ProtobufParser.ExtensionRangeDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.tagRanges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTagRanges([NotNull] ProtobufParser.TagRangesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.tagRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTagRange([NotNull] ProtobufParser.TagRangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.tagRangeStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTagRangeStart([NotNull] ProtobufParser.TagRangeStartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.tagRangeEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTagRangeEnd([NotNull] ProtobufParser.TagRangeEndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageReservedDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageReservedDecl([NotNull] ProtobufParser.MessageReservedDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNames([NotNull] ProtobufParser.NamesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.enumDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDecl([NotNull] ProtobufParser.EnumDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumName([NotNull] ProtobufParser.EnumNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.enumElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumElement([NotNull] ProtobufParser.EnumElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.enumValueDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueDecl([NotNull] ProtobufParser.EnumValueDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.enumValueName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueName([NotNull] ProtobufParser.EnumValueNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.enumValueNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueNumber([NotNull] ProtobufParser.EnumValueNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.enumReservedDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumReservedDecl([NotNull] ProtobufParser.EnumReservedDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.enumValueRanges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueRanges([NotNull] ProtobufParser.EnumValueRangesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.enumValueRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueRange([NotNull] ProtobufParser.EnumValueRangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.enumValueRangeStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueRangeStart([NotNull] ProtobufParser.EnumValueRangeStartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.enumValueRangeEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueRangeEnd([NotNull] ProtobufParser.EnumValueRangeEndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.extensionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtensionDecl([NotNull] ProtobufParser.ExtensionDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.extendedMessage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendedMessage([NotNull] ProtobufParser.ExtendedMessageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.extensionElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtensionElement([NotNull] ProtobufParser.ExtensionElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.extensionFieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtensionFieldDecl([NotNull] ProtobufParser.ExtensionFieldDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.serviceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceDecl([NotNull] ProtobufParser.ServiceDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.serviceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceName([NotNull] ProtobufParser.ServiceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.serviceElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceElement([NotNull] ProtobufParser.ServiceElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.methodDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDecl([NotNull] ProtobufParser.MethodDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodName([NotNull] ProtobufParser.MethodNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.inputType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputType([NotNull] ProtobufParser.InputTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.outputType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputType([NotNull] ProtobufParser.OutputTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.methodElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodElement([NotNull] ProtobufParser.MethodElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.messageType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageType([NotNull] ProtobufParser.MessageTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] ProtobufParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.alwaysIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlwaysIdent([NotNull] ProtobufParser.AlwaysIdentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtobufParser.sometimesIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSometimesIdent([NotNull] ProtobufParser.SometimesIdentContext context);
}
